spring:
  application:
    name: serviceregistry
    
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}